### ISSUE TITLE
Hook - Get controller name and action name inside of hook

### ISSUE THREAD

**Issue by lucasmonstrox** [n0m0r3pa1n/sails_params_roles_validation#1]
Hey m8, are you fine?

I'm trying to create a hook with the same way of your project.

It is possible to get the controller and name of current url inside in hook?

I need to create a layer for validation, without policies and after policies... :'( Is not easy to find some solution.

**Comment by n0m0r3pa1n** [comment]
Hey,
you need to access the req.options field. Here it is how it looks like:

```
{ 
  detectedVerb: { verb: 'all', original: '/*', path: '/*' },
  controller: 'auth',
  action: 'login',
  validation: 'login',
  skipRegex: [],
  _middlewareType: 'CSRF HOOK: CSRF' 
}
```

Here is what the policy looks like:

```
module.exports = function modelValidation(req, res, next) {
  console.log(req.options);
  // ...
  return next();
}
```

**Comment by lucasmonstrox** [comment]
@n0m0r3pa1n really thanks my friend :-) U resolved my big problem :-P

Sailsjs dont have dispatch events, so, it is impossible to inject some code after/before policies.

BUT -> My validator can be a police and works like a charm :-D
